---
- name: Deploying your A2
  hosts: all
  remote_user: root
  become: true
  become_method: sudo
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  vars:
      repository_path: /home/vagrant/podcasts-search
  tasks:
    - name: Add repositories
      apt_repository: repo='ppa:webupd8team/java' state=present
    - name: Install necessary packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - openjdk-7-jre
        - oracle-java8-installer
    - name: Check if directory exists
      stat: path='{{ repository_path }}'
    - name: Download Elasticsearch
      command: wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb
      register: setup
      when: setup.stat.exists == false
      args:
        chdir: '{{ repository_path }}'
    - name: Install Elasticsearch
      command: sudo dpkg -i elasticsearch-1.7.2.deb
      when: setup.stat.exists == false
      args:
        chdir: '{{ repository_path }}'
    - name: Add init-script to runlevels
      command: sudo update-rc.d elasticsearch defaults
      when: setup.stat.exists == false
      args:
        chdir: '{{ repository_path }}'
    - name: Copy Upstart configuration
      template: src=upstart.conf.j2 dest=/etc/init/upstart.conf
    - name: Make sure our server is running
      service: name=upstart state=started
    - name: Copy Nginx site values
      template: src=a3.nginx.j2 dest=/etc/nginx/sites-enabled/a3
      notify:
        - restart nginx
    - name: Remove any default sites
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx
    - name: Make sure nginx is running
      service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
