branch-defaults:
  master:
    environment: tcat-dev-env-1
    group_suffix: null
global:
  application_name: tcat-dev
  branch: null
  default_ec2_keyname: tcatkp
  default_platform: python3.4
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
