branch-defaults:
  master:
    environment: tcatdev-env
environment-defaults:
  tcatdev-env:
    branch: null
    repository: null
global:
  application_name: TCAT-Dev
  default_ec2_keyname: tcat-dev
  default_platform: python3.4
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
