apiVersion: v1
kind: Service
metadata:
  labels:
    name: podcast
    podcastService: podcast
  name: podcast
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: podcast
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
