---
- name: AWS Single Node deployment
  hosts: all
  remote_user: root
  become: true
  become_method: sudo
  vars:
    docker_compose_path: "*"
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  taks:
    - name: update
      apt:
        upgrade: yes
        update_cache: yes
    - name: install docker
      include_role: 
        name: docker