--- 
- name: ec2 docker deployment
  hosts: all
  remote_user: root
  become: true
  become_method: sudo
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  tasks:
    - name: update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
    - name: install docker
      include_role: 
        name: docker
    - name: remove docker containers and images
      shell: |
        sudo docker kill $(sudo docker ps -q)
        sudo docker rm $(sudo docker ps -a -q)
        sudo docker rmi $(sudo docker images -q)
      ignore_errors: yes
    - name: run docker compose
      docker_service:
        project_src: docker-compose
        state: present
    - name: wait for server
      wait_for:
        port: 80
        delay: 10