Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"
  
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'site.yml'
    ansible.verbose = 'vvv'
  end
end
