version: "2"

services:
  node:
    build: node
    image: tcat-node
    environment:
      PORT: 80
      REGISTERTOKEN: 9c9220074b050b75b4539d78ea5c721bd6a0d689
      TOKEN: ZG9QcmQ1SXE2M3RmSUVfSzI3QzJyOThTSVhNYTpIY2g3bXh1dUh3Y29HdE5WTmxXNTBxNDlGdThh
    network_mode: "host"
    ports:
      - "80:80"
  ghopper:
    build: ghopper
    image: tcat-ghopper
    network_mode: "host"
    ports:
      - "8988:8988"
  map:
    build: map
    image: tcat-map
    network_mode: "host"
    ports:
      - "8989:8989"
  ghopper-walking:
    build: ghopper-walking
    image: tcat-ghopper-walking
    network_mode: "host"
    ports:
      - "8987:8987"
