"""empty message

Revision ID: e42d4f566b07
Revises: 9d73ebdde832
Create Date: 2017-08-24 23:28:45.771877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42d4f566b07'
down_revision = '9d73ebdde832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_creds', 'spotify_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_creds', 'spotify_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
