apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
    redisService: redis
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
