CREATE TABLE IF NOT EXISTS users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  googleId VARCHAR(30) NOT NULL,
  netId VARCHAR(30) NOT NULL,
  firstName VARCHAR(30),
  lastName VARCHAR(30),
  email VARCHAR(30),
  createdAt INT(32) DEFAULT UNIX_TIMESTAMP(),
  updatedAt INT(32) DEFAULT UNIX_TIMESTAMP() ON UPDATE UNIX_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS sessions (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY);
