CREATE TABLE IF NOT EXISTS users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  googleId VARCHAR(30) NOT NULL,
  netId VARCHAR(30) NOT NULL,
  firstName VARCHAR(30),
  lastName VARCHAR(30),
  email VARCHAR(30),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
