---
# roles/deploy/tasks/main.yml

- name: Install git
  apt:
    pkg: git
    state: present
  sudo: yes

- name: Create www directory
  file:
    path: /srv/www
    owner: ubuntu
    group: ubuntu
    state: directory
  sudo: yes

- name: Clone app repository
  git:
    repo: "{{ repository_git_path }}"
    dest: "{{ repository_path }}"
    version: master

- name: Clone osrm repository
  git:
    repo: "{{ repository_git_path_osrm }}"
    dest: "{{ repository_path_osrm }}"
    version: master    

- name: Cmake osrm
  command: cmake -DENABLE_MASON=ON -DENABLE_NODE_BINDINGS=ON ..
  args:
    chdir: "{{ repository_path_osrm }}/build"
    creates: "{{ repository_path_osrm }}/build"

- name: Make osrm
  command: make
  args:
    chdir: "{{ repository_path_osrm }}/build"

- name: NPM link
  command: npm link
  args:
    chdir: "{{ repository_path }}" 

- name: NPM link osrm
  command: npm link osrm
  args:
    chdir: "{{ repository_path }}"     

- name: NPM link appdev
  command: npm link appdev
  args:
    chdir: "{{ repository_path }}"    

- name: lua Commands
  command: node_modules/osrm/lib/binding/osrm-extract osrm/map.osm -p node_modules/osrm/profiles/foot.lua
  args:
    chdir: "{{ repository_path }}"   

- name: osrm Commands
  command: node_modules/osrm/lib/binding/osrm-contract osrm/map.osrm
  args:
    chdir: "{{ repository_path }}"  

- name: moving osrm folder
  command: mv *.osm* ./osrm; mv *.osrm* ./osrm
  args:
    chdir: "{{ repository_path }}"  
    creates: "{{ repository_path }}/osrm"

- name: Install upstart script
  copy:
    src: upstart.conf
    dest: /etc/upstart/webapp.conf
  sudo: yes

- name: Enable and start the application
  service:
    name: webapp
    enabled: yes
    state: restarted
  sudo: yes
