default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cuappdev_site_v3

test:
  <<: *default
  database: cuappdev_site_v3_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: cuappdev_site
  username: cuappdev
  password: <%= ENV["CUAPPDEV_SITE_PASS"] %>