CREATE TABLE IF NOT EXISTS users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  netId VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject VARCHAR(30) NOT NULL,
  name VARCHAR (30) NOT NULL,
  number INT(6) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS owned_course (
  user_id INT(6) UNSIGNED NOT NULL,
  course_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (course_id) REFERENCES courses(id),
  PRIMARY KEY (user_id, course_id)
);
