--- 
- name: ec2 docker deployment - deploy
  hosts: all
  gather_facts: False
  become: yes
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  tasks:
    - name: remove docker containers and images
      shell: |
        sudo docker kill $(sudo docker ps -q)
        sudo docker rm $(sudo docker ps -a -q)
        sudo docker rmi $(sudo docker images -q)
      ignore_errors: yes
    - name: copy docker compose
      copy:
        src: docker-compose
        dest: /usr/src/deploy
    - name: run docker compose
      docker_service:
        project_src: /usr/src/deploy/docker-compose
        state: present
    - name: wait for server
      wait_for:
        port: 80
        delay: 10
