--- 
- name: ec2 docker deployment - setup
  hosts: all
  gather_facts: False
  become: yes
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  tasks:
    - name: install python 2
      raw: apt -y update && apt install -y python python-dev python-pip
    - name: Ensure Docker dependencies are installed.
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
    - name: add docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      register: add_repository_key
      ignore_errors: true
    - name: add docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
        update_cache: yes
    - name: install docker
      package: 
        name: docker-ce 
        state: present
    - name: enable docker at boot
      service:
        name: docker
        state: started
        enabled: yes
    - name: install docker python packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-compose